version: '3'
services:
  db:
    image: mysql/mysql-server
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password57588
      MYSQL_DATABASE: POS
      MYSQL_USER: user
      MYSQL_PASSWORD: password57588
    ports:
      - "3306:3306"


volumes:
  db_data:
