"""empty message

Revision ID: 0d6b7f507dbc
Revises: bf293f12d113
Create Date: 2000-01-01 07:15:41.621586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6b7f507dbc'
down_revision = 'bf293f12d113'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
