"""empty message

Revision ID: 39605732f074
Revises: 52abc4c5fcb0
Create Date: 2023-05-06 20:12:55.618715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39605732f074'
down_revision = '52abc4c5fcb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
