"""empty message

Revision ID: 5fa2d1f6d249
Revises: 39605732f074
Create Date: 2023-05-06 20:14:10.382346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa2d1f6d249'
down_revision = '39605732f074'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
