"""empty message

Revision ID: a363383712ea
Revises: 5e8a842cbc0e
Create Date: 2023-05-06 17:01:19.832594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a363383712ea'
down_revision = '5e8a842cbc0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
