"""empty message

Revision ID: ca432ea26a11
Revises: 0d6b7f507dbc
Create Date: 2000-01-01 07:17:37.406122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca432ea26a11'
down_revision = '0d6b7f507dbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('notif', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'notif')
    # ### end Alembic commands ###
